version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - backend-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: NeoDBmvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - backend-network

  deal-service:
    build:
      context: ./deal-service
      dockerfile: Dockerfile
    container_name: deal-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_APPLICATION_NAME: deal-service
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deal_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    networks:
      - backend-network
    depends_on:
      - postgres
      - kafka

  calculator-service:
    build:
      context: ./calculator-service
      dockerfile: Dockerfile
    container_name: calculator-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_APPLICATION_NAME: calculator
      DEAL_SERVICE_URL: http://deal-service:8083
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - backend-network
    depends_on:
      - deal-service

  statement-service:
    build:
      context: ./statement-service
      dockerfile: Dockerfile
    container_name: statement-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_APPLICATION_NAME: statement-service
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - backend-network
    depends_on:
      - kafka

  dossier-service:
    build:
      context: ./dossier-service
      dockerfile: Dockerfile
    container_name: dossier-service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_APPLICATION_NAME: dossier
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - backend-network
    depends_on:
      - kafka

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: